[build-dependencies]
pkg-config = "0.3.7"

[dependencies]
atk-sys = "0.8.0"
cairo-sys-rs = "0.8.0"
gdk-pixbuf-sys = "0.8.0"
gdk-sys = "0.8.0"
gio-sys = "0.8.0"
glib-sys = "0.8.0"
gobject-sys = "0.8.0"
pango-sys = "0.8.0"
libc = "0.2"

[dev-dependencies]
shell-words = "0.1.0"
tempdir = "0.3"

[features]
dox = []
v3_16 = []
v3_18 = ["v3_16"]
v3_20 = ["v3_18"]
v3_22 = ["v3_20"]
v3_22_26 = ["v3_22_6"]
v3_22_27 = ["v3_22_26"]
v3_22_29 = ["v3_22_27"]
v3_22_30 = ["v3_22_29"]
v3_22_6 = ["v3_22"]
v3_24 = ["v3_22_30"]

[lib]
name = "gtk_sys"

[package]
authors = ["The Gtk-rs Project Developers"]
build = "build.rs"
description = "FFI bindings to libgtk-3"
homepage = "http://gtk-rs.org/"
keywords = ["gtk", "ffi", "gtk-rs", "gnome"]
license = "MIT"
links = "gtk"
name = "gtk-sys"
repository = "https://github.com/gtk-rs/sys"
version = "0.8.0"
