[package]
name = "gobject-sys-test"
version = "0.1.0"
authors = ["Tomasz MiÄ…sko <tomasz.miasko@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
gobject-sys = { path = "../gobject-sys" }
libc = "0.2"

[build-dependencies]
ctest = "0.2"
shell-words = "0.1.0"

